server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/productservice
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto : update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:8082


#eureka:
#  instances:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:9090/eureka}